language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t karandhingra/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true karandhingra/docker-react npm run test 
